name: copd-paper
channels:
    - defaults
dependencies:
    - dask=2.10.1
    - ipykernel
    - matplotlib=3.1.2
    - numpy=1.18.5
    - pandas=1.0.1
    - pip=19.3.1
    - python=3.7.6
    - scipy=1.5
    - pip:
        - ciw==2.0.1
        - git+https://github.com/daffidwilde/kmodes@v0.9.1
        - yellowbrick==1.0.1
