name: edo-exp
channels:
  - conda-forge
  - defaults
dependencies:
  - dask=1.2.0
  - numpy=1.16.2
  - pandas=0.24.2
  - pip=19.0.3
  - python=3.6.8
  - scikit-learn=0.20.3
  - scipy=1.3.1
  - yaml=0.1.7
  - pip:
    - alphashape==1.0.1
    - descartes==1.1.0
    - edo==0.2.1
    - shapely==1.6.4.post2
