name: CI

on:
    push:
    schedule:
    - cron: "0 0 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install latex libs
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra
          sudo apt-get install -y texlive-xetex
          sudo apt-get install latexmk
          sudo apt-get install texlive-science
          sudo apt-get install aspell aspell-en

      - name: Install fonts
        run: |
          sudo apt-get install -y texlive-fonts-extra
          sudo curl --remote-name https://www.tug.org/fonts/getnonfreefonts/install-getnonfreefonts
          sudo texlua install-getnonfreefonts
          sudo getnonfreefonts --sys garamondx
          sudo getnonfreefonts --sys -r

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Combine and clean bibliography
        run: inv bibliography
      - name: Test PDF compiles
        run: inv compile --engine=xelatex
      - name: Doctest source
        run: inv doctest
      - name: Test spellcheck
        run: inv spellcheck
