name: CI for thesis

on:
    push:
    schedule:
    - cron: "0 0 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up miniconda and environment
        uses: goanpeca/setup-miniconda@v1.6.0
        with:
          environment-file: ./environment.yml
          activate-environment: 'thesis'
      - name: Print conda and Python information
        run: |
          conda info
          which python
          python --version
      - name: Install latex libs
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra
          sudo apt-get install -y texlive-xetex
          sudo apt-get install latexmk
          sudo apt-get install texlive-science
          sudo apt-get install aspell aspell-en

      - name: Install fonts
        run: |
          sudo apt-get install -y texlive-fonts-extra
          sudo curl --remote-name https://www.tug.org/fonts/getnonfreefonts/install-getnonfreefonts
          sudo texlua install-getnonfreefonts
          sudo getnonfreefonts --sys garamondx
          sudo getnonfreefonts --sys -r

      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Combine and clean bibliography
        run: python -m invoke bibliography
      - name: Test PDF compiles
        run: python -m invoke compile --engine=xelatex
      - name: Doctest source
        run: python -m invoke doctest
      - name: Test spellcheck
        run: python -m invoke spellcheck
