name: CI

on:
    push:
    schedule:
    - cron: "0 0 * * 0"

jobs:
    build:

        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 4
            matrix:
                os: [ubuntu-latest]
                python-version: [3.7]

        steps:
        - uses: actions/checkout@v1
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install latex libs
          run: |
            sudo apt-get update
            sudo apt-get install -y texlive-latex-extra
            sudo apt-get install -y texlive-xetex
            sudo apt-get install latexmk
            sudo apt-get install texlive-science
            sudo apt-get install aspell aspell-en
        - name: Install Garamond font
          run: |
            sudo curl --remote-name https://www.tug.org/fonts/getnonfreefonts/install-getnonfreefonts
            sudo texlua install-getnonfreefonts
            sudo getnonfreefonts --sys garamondx
            sudo getnonfreefonts --sys -r
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Clone submodules
          run: |
            git submodule update --init --recursive
        - name: Combine and clean bibliography
          run: |
            inv bibliography
        - name: Test PDF compiles
          run: |
            inv compile
        - name: Test spellcheck
          run: |
            inv spellcheck
