name: Comment word count when asked with @wordcount

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check for comment call
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@wordcount'
          reaction: eyes
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install TeXcount
        run: |
            sudo apt-get update
            sudo apt-get install -y texlive-extra-utils
      - name: Clone submodules
        run: git submodule update --init --recursive
      - name: Calculate word count
        run: python count.py
      - name: Comment current wordcount
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "I can see you've asked for me."
