name: Comment word count when asked with @wordcount

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest
    outputs:
      count: ${{ steps.count.outputs.word_count }}
    steps:
      - name: Check for comment call
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@wordcount'
          reaction: eyes
          prefix_only: 'true'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install TeXcount
        run: |
            sudo apt-get update
            sudo apt-get install -y texlive-extra-utils
      - name: Clone submodules
        run: git submodule update --init --recursive
      - name: Calculate word count
        id: count
        run: |
          WORD_COUNT = $(python count.py)
          WORD_COUNT = "${WORD_COUNT//$'\n'/'%0A'}"
          echo "::set-output name=word_count::$WORD_COUNT"
      - name: Comment current wordcount
        if: ${{ steps.check.outputs.triggered == 'true' }}
        uses: thollander/actions-comment-pull-request@master
        with:
          message: ${{ steps.count.outputs.word_count }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
